language: cpp

compiler:
  - gcc
  - clang

os: linux
dist: bionic

addons:
  apt:
    packages:
      - cmake
      - catch

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1 rstd_test
  - ./rstd_test
