language: cpp

compiler:
  - gcc
  - clang

os: linux
dist: bionic

addons:
  apt:
    packages:
      - cmake
      - catch

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1 test_rstd
  - ./test_rstd
  - make VERBOSE=1 self_test_rstd
  - ./self_test_rstd
