language: cpp

compiler:
  - gcc
  - clang

os: linux
dist: bionic

addons:
  apt:
    packages:
      - cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make rstd_test -j $(grep -c ^processor /proc/cpuinfo)
  - ./rstd_test
