language: cpp

compiler:
  - gcc
  - clang

os: linux

addons:
  apt:
    packages:
      - cmake
      - catch

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --verbose
